### ISSUE TITLE
Create a Base Python Work

### ISSUE THREAD

**Issue by Jacob-Gregor** [Gregorvich/dungeon-omega#1]
This project will be written in Python. This is to both expand your skill  set but also take advantage of my expertise.

Before I get into what we are going to build, I want to focus on the fundamentals. The purpose of this first task is to introduce you to Python and to make sure you understand the GitHub practice we will be following. 

- You will have a main.py class that I will call that will accomplish whatever work you want. It can be hard coded multiplication, it can be  more advanced "Hello World", or whatever. 
- Your code must have multiple functions.
- Your code should not be in the root directory of the GitHub project
- You will not push your code directly into the Master branch. You will either push your changes into a different branch and create a Pull Request or fork this GitHub repo and create a Pull Request through that method.
- Once you create a Pull Request, I will review it. I will "request changes" in the Pull Request if I think you did not accomplish one of the tasks above or if the code you wish to merge into the master branch is written poorly. If your code looks good, I will merge it.
- I expect work updates to be posted in this issue. So if you get a part of your work done or get stuck, make note of that here. This will tell me you are actively working on this Task and I can provide feedback if you ask for it.

That is it. If you have questions, let me know. Otherwise I expect to either see comments in this issue of your progress. Examples:  you are stuck, you are busy for the next few days, or you plan on getting the main work done by Friday, etc.

 **There is no due date for this task. But if you do not keep me up to date with your progress, I will not help with this project.**

**Comment by Jacob-Gregor** [comment]
No updates either in this issue or through any other means from the last 16 days. Closing issue. The issue will reopen once I hear from @Gregorvich that  he wants to work on this and starts communicating in this issue.

**Comment by Jacob-Gregor** [comment]
From @Gregorvich:
As you know I had a busy last few weeks, but I guess that's no excuse for not posting updates on this project. At any rate, I will try to be more consistent with my updates on the tasks at hand moving forward.

Here's the game plan moving forward in terms of what the closed issue talked about:
- I will build the Hello World program using at least two functions (probably a main function that calls the "Hello World" function, but I guess all projects need a function called "main" in order for the compiler to work without complaint. Lol)
- As I do the previous task I will figure out how to upload the files to Github using the Git application. I am a bit rusty on using Version Control but learning that will be the fun part
- I will NOT work on the master branch/ merge directly into the master branch because that would be silly. I will create my own branch which will be reviewed by the team before merging or something like that.
- Since this is a pretty basic task I don't think I will have many questions, but if I come across something related to proper Github usage or something Python related, I will ask Senpai.

There you have it. In terms of the completion date for this task, I will try to have it done by Thursday night, or Friday at the latest.

**Comment by Jacob-Gregor** [comment]
I do not know if "Thursday night or Friday" means 05/27 or 06/03. But either way let me know if you have any questions and create a PR for me to review when you are done with your work.

**Comment by Jacob-Gregor** [comment]
What is your estimate time on completion of this issue? Do you have any questions I can help with?

**Comment by Gregorvich** [comment]
Hey Jacob, sorry for the late response. I think with my Rochester Doctor appointments that I had last month I fell out of the routine of regularly updating the project. At any rate, I will have something you can review by Thursday night (June 25). Thanks for your patience, and I hope the family is doing well haha.

As always, I will let you know if I have any questions.

**Comment by Gregorvich** [comment]
Hey Jacob, I know it's been like a month since I last posted an update on this issue, but what can you do, you know? My plan before this coming Wednesday is to have a program uploaded onto Github that you can look at. Over the past few weeks I've been reviewing some OOP concepts using the C++ Language, so that'll probably help with our future work on the shopping cart. I will post something by Wednesday night, June 29.

Hopefully the family is doing well, talk to you soon!

**Comment by Jacob-Gregor** [comment]
I was waiting to see what you'll be posting, but since it is past our agreed post time, I will go ahead and make sure you remember one important thing about this work. It needs to be written in Python! Though if you have something in C++ I'd be interested in seeing it.

**Comment by Gregorvich** [comment]
Okay, I will be sure to write it in Python. Either would be fine but I don't mind working in Python. I fell behind this week on some things, but I will be sure to post something by Monday. Thanks for your patience.

**Comment by Jacob-Gregor** [comment]
I have not heard or seen an update from you since Monday. Are you stuck? Is there a reason you are not posting updates? Do you need for me to give a thumbs up on all your comments so you know I've read them?

**Comment by Gregorvich** [comment]
Hey Jacob. I will post something on here by tomorrow night. I had some computer issues that I had to resolve, and then I reviewed some stuff with Git and version control. I guess those sound like excuses, but there you have it. I was also going to call yesterday but some stuff came up. At any rate, I will have something for you by tomorrow night 6:00 p.m. The project sounds exciting, so it is definitely something I think we should still do.

What IDE do you use for Python by the way, Eclipse? Also, do you want to use Skype or Zoom for our video conferences? I've heard that you can contract the Coronavirus over Zoom, but these are mostly unconfirmed rumors. Let me know!

Thanks,
Adam

**Comment by Jacob-Gregor** [comment]
I use JetBrains PyCharm: https://www.jetbrains.com/pycharm/download/#section=windows

**Comment by Jacob-Gregor** [comment]
We can look into using Skype or Zoom down the road once you start running into roadblocks while working on these tasks. Otherwise lets stick to discussing problems or questions on GitHub issues or PRs for now.

**Comment by Gregorvich** [comment]
Just a quick update since I was already pretty thorough in the pull request. I created a python program and tested it to make sure it behaved appropriately. I did this in a branch separate from master, and, once finished, I created a pull request. The program is pretty cool, you can adjust whether a book has a forbidden spell, and if it does you won't be able to print it. I named the branch serverfix, which isn't really related to what the branch is about. Let me know if there is more I should do before you are able to accept my pull request.

I'm not exactly sure what the next step will be, and we are still early in the project, so I didn't stress too much over what I named things such as the branches, but we should still discuss what are good naming conventions and stuff like that.

**Comment by Jacob-Gregor** [comment]
https://github.com/Gregorvich/dungeon-omega/pull/3 addresses this issue. Closing.
